In [42]:
import mlx.core as mx
import mlx_lm
from mlx_lm.utils import load, save_config
import pprint
import numpy as np
np.set_printoptions(threshold=1000)  # 1000 es el valor por defecto en muchas instalaciones de NumPy

Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 81707.22it/s]


In [44]:
model, tokenizer = load("microsoft/phi-1.5")
model.eval()

Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 77512.80it/s]


Model(
  (model): PhiModel(
    (embed_tokens): Embedding(51200, 2048)
    (layers.0): PhiDecoderLayer(
      (self_attn): PhiAttention(
        (q_proj): Linear(input_dims=2048, output_dims=2048, bias=True)
        (k_proj): Linear(input_dims=2048, output_dims=2048, bias=True)
        (v_proj): Linear(input_dims=2048, output_dims=2048, bias=True)
        (dense): Linear(input_dims=2048, output_dims=2048, bias=True)
        (rope): RoPE(32, traditional=False)
      )
      (input_layernorm): LayerNorm(2048, eps=1e-05, affine=True)
      (mlp): PhiMLP(
        (fc1): Linear(input_dims=2048, output_dims=8192, bias=True)
        (fc2): Linear(input_dims=8192, output_dims=2048, bias=True)
        (act): GELU()
      )
    )
    (layers.1): PhiDecoderLayer(
      (self_attn): PhiAttention(
        (q_proj): Linear(input_dims=2048, output_dims=2048, bias=True)
        (k_proj): Linear(input_dims=2048, output_dims=2048, bias=True)
        (v_proj): Linear(input_dims=2048, output_dims=2048, bi

In [9]:
from mlx_lm.utils import load, save_config


In [10]:
model, tokenizer = load("microsoft/phi-1.5") 

Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 58798.65it/s]


In [5]:
sample = {"text": "\nC Read the scenario and question below, then choose the most appropriate answer from the options given (1, 2, or 3). Respond with the number of the correct answer based on the scenario's context and the question's implications.Austin raised the stake to the level of the top of the wall.\nQ What will Austin want to do next? <answer1>sit on the wall</answer1> <answer2>tie the stake</answer2> <answer3>measure something on the wall</answer3>\nA 2"}

In [59]:
batch = [tokenizer.encode(sample[j]) for j in sample]


In [70]:
import pprint

In [86]:
import numpy as np
np.set_printoptions(threshold=1000)  # 1000 es el valor por defecto en muchas instalaciones de NumPy

print(np.array(batch))

[[  198    34  4149   262  8883   290  1808  2174    11   788  3853   262
    749  5035  3280   422   262  3689  1813   357    16    11   362    11
    393   513   737 33556   351   262  1271   286   262  3376  3280  1912
    319   262  8883   338  4732   290   262  1808   338 10939    13 40245
   4376   262 10171   284   262  1241   286   262  1353   286   262  3355
     13   198    48  1867   481  9533   765   284   466  1306    30  1279
  41484    16    29 48937   319   262  3355  3556 41484    16    29  1279
  41484    17    29 36224   262 10171  3556 41484    17    29  1279 41484
     18    29  1326  5015  1223   319   262  3355  3556 41484    18    29
    198    32   362]]


In [89]:
a == np.array(batch)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]])

In [88]:
a = [198, 34, 4149, 262, 8883, 290, 1808, 2174, 11, 788, 3853, 262, 749, 5035, 3280, 422, 262, 3689, 1813, 357, 16, 11, 362, 11, 393, 513, 737, 33556, 351, 262, 1271, 286, 262, 3376, 3280, 1912, 319, 262, 8883, 338, 4732, 290, 262, 1808, 338, 10939, 13, 40245, 4376, 262, 10171, 284, 262, 1241, 286, 262, 1353, 286, 262, 3355, 13, 198, 48, 1867, 481, 9533, 765, 284, 466, 1306, 30, 1279, 41484, 16, 29, 48937, 319, 262, 3355, 3556, 41484, 16, 29, 1279, 41484, 17, 29, 36224, 262, 10171, 3556, 41484, 17, 29, 1279, 41484, 18, 29, 1326, 5015, 1223, 319, 262, 3355, 3556, 41484, 18, 29, 198, 32, 362]

In [60]:
import mlx.core as mx


In [61]:
batch =  mx.array(batch)

In [90]:
logits, _ = model(batch)
logits = logits.astype(mx.float32)

In [94]:
logits.shape

(1, 111, 51200)

In [95]:
last_token = logits[:,-2,:]

In [96]:
type(last_token)


mlx.core.array

In [97]:
last_token

array([[13.6328, 12.5703, 13.9922, ..., 3.10742, 3.10547, 3.10547]], dtype=float32)

In [98]:
import numpy as np

predictions = np.argmax(last_token)
type(predictions)

numpy.int64

In [101]:
predictions

352

In [102]:
tokenizer.convert_ids_to_tokens(352)

'Ġ1'

In [166]:
sample = {"text": "\nC Read the scenario and question below, then choose the most appropriate answer from the options given (1, 2, or 3). Respond with the number of the correct answer based on the scenario's context and the question's implications.Sasha got home and took her dog for a long walk to get it some exercise.\nQ What does Sasha need to do before this? <answer1>give the dog treats</answer1> <answer2>finish walking her dog</answer2> <answer3>grab some bags to clean up</answer3>\nA 3"}



batch = [tokenizer.encode(sample[j]) for j in sample]


In [167]:
tokenizer.decode(np.array(batch)[0][-1])

'3'

In [168]:
np.array(batch).shape

(1, 128)

In [178]:
#model, tokenizer = load("microsoft/phi-1.5") 
model, tokenizer = load("mistralai/Mistral-7B-v0.1") 


In [179]:
batch =  mx.array(batch)
logits, _ = model(batch)
logits = logits.astype(mx.float32)
last_token = logits[0,-2,:]
predictions = np.argmax(last_token)
print(tokenizer.decode(predictions))
predictions

2


28750

In [180]:
k = 4  # Ajusta k según cuántos tokens superiores quieras obtener

# Usar np.argsort para ordenar los índices basados en los valores de logits, tomar los últimos k elementos:
top_indices = np.argsort(last_token)[-k:]

# Decodificar cada uno de los top k indices usando el tokenizer
decoded_tokens = [tokenizer.decode([idx]) for idx in top_indices]

# Imprimir los tokens decodificados
print(decoded_tokens)

['<', '3', '1', '2']


In [182]:
top_indices

array([  523, 28770, 28740, 28750])

In [173]:
for i in range (1,10):
    last_token = logits[0,-10+i,:]
    type(last_token)
    predictions = np.argmax(last_token)
    print(tokenizer.decode(predictions))

after
answer
3
>






2


